config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/ask', to: 'questions#ask'
  get '/answer', to: 'questions#answer'
  root to: 'questions#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end

  def answer
    @question = params[:ask]
    if @question.include?('?')
      @coach = 'Silly question, get dressed and go to work!'
    elsif @question == 'I am going to work'
      @coach = 'Great!'
    else
      @coach = 'I don`t care, get dressed and do to work!'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  </head>

  <body>
      <div style="background: lightgray; padding:10px">
        <h3>CoachApp</h3>
      </div>
      <div class="d-flex justify-content-center py-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/answer.html.erb
<div class="d-flex justify-content-center p-5">
  <div class="card" style="width: 25rem;">
    <div class="card-body">
      <h2 class="card-title border p-1">Check out your coach´s answer!</h2>
      <h4 class="card-subtitle mb-2 text-muted">Here it is:</h4>
      <h5 class="card-text"><%= @coach %></h5>
      <div class="card-footer text-muted">

          <div class="d-inline-flex p-2">
              <span class="border border-primary rounded p-1">
              <%= link_to "Ask Page", ask_path %>
              </span>

              <span class="border border-primary rounded p-1">
              <%= link_to "Home", root_path %>
              </span>

          </div>

    </div>
  </div>
</div>

app/views/questions/ask.html.erb
<div class="d-flex justify-content py-5">
  <form action="/answer" method="get">
  <div class="form-group">
    <label for="exampleInputEmail1">What do you want to know?</label>
    <input type="text" class="form-control" name="ask" placeholder="Enter your question">
    <input class="btn btn-info" type="submit" value="Ask!">
  </div>
  <div class="card-footer text-muted">

    <div class="d-flex justify-content-between">
        <span class="border border-primary rounded p-1">
        <%= link_to "Answer Page", answer_path %>
        </span>

        <span class="border border-primary rounded p-1">
        <%= link_to "Home", root_path %>
        </span>

    </div>

  </div>
  </form>
</div>

app/views/questions/home.html.erb
<h1>This is our home page</h1>

<%= link_to "Answer Page", answer_path %>
<%= link_to "Ask Page", ask_path %>